name: axis
description: Axis VPN client for Windows.
publish_to: 'none'
version: 1.2.0+120

environment:
  sdk: ^3.11.5

dependencies:
  flutter:
    sdk: flutter
  path: ^1.8.3
  http: ^1.6.0
  flutter_colorpicker: ^1.1.0
  system_tray: ^2.0.3
  url_launcher: ^6.3.2
  country_flags: ^4.1.2

dev_dependencies:
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  image_path: "assets/axis_icon.png" # твой исходник
  windows:
    generate: true
    icon_size: 256  

flutter:
  uses-material-design: true
  assets:
    - assets/bin/mihomo.exe
    - assets/bin/wintun.dll
    - assets/shield.ico
    - assets/shield.png
    - assets/tray_connected.ico
    - assets/tray_disconnected.ico
    - assets/axis_icon.svg
    - assets/axis_icon_connected.svg
    - assets/axis_icon_disconnected.svg
